<?xml version="1.0" ?>
<robot name="digr" xmlsn:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find description)/urdf/common_properties.xacro"/>
	<xacro:include filename="$(find description)/urdf/digr.gazebo.xacro"/>
	
	<!-- Define colors -->
	
	<!-- All units in meters, kg, seconds, rads -->
	<!-- Equation for inertial matrix of box/prisim -->
	<xacro:macro name="box_inertial_matrix" params="m l w h">
		<inertia ixx="${(m*(w*w+h*h))/12.0}" ixy = "0" ixz = "0"
				 iyy="${(m*(l*l+h*h))/12.0}" iyz = "0"
				 izz="${(m*(l*l+w*w))/12.0}" />
	</xacro:macro>
	<!-- Equation for inertial matrix of cylinder (rotating around y axis) -->
	<xacro:macro name="cylinder_inertia" params="m r h">
		<inertia ixx="${(m*(3*r*r+h*h))/12.0}" ixy = "0" ixz = "0"
				 iyy="${m*r*r/2}"			   iyz = "0"
				 izz="${(m*(3*r*r+h*h))/12.0}"  />
	</xacro:macro>
	
	<!-- Main dimensions: meters, kg, seconds, rads -->
	<xacro:property name="PI" value="3.1415926535897931" />
	
	<xacro:property name="base_height" value="0.690" />
	<xacro:property name="base_length" value="0.740" />
	<xacro:property name="base_width" value="0.865" />
	<xacro:property name="base_mass" value="72" />
	
	<xacro:property name="base_x_origin_to_wheel_origin" value="0.29125" />
	<xacro:property name="base_y_origin_to_wheel_origin" value="0.190" />
	<xacro:property name="base_height_origin_to_wheel_origin" value="0.103" />
	
	<xacro:property name="wheel_radius" value="0.174" />
	<xacro:property name="wheel_height" value="0.15" />
	<xacro:property name="wheel_mass" value="2" />
	
	<xacro:property name="imu_length" value="" />
	<xacro:property name="imu_width" value="" />
	<xacro:property name="imu_height" value="" />
	
	<!-- World Origin -->
	<!-- world_origin is a fictitious link(frame) that is on the ground right below base_link origin -->
	<!-- z axis is height -->
	<link name="world_origin"/>
	
	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 ${wheel_radius - base_hight_to_wheel_origin}" rpy="0 0 0" />
		<parent link="world_origin" />
		<child link="base_link" />
	</joint>
	
	<link name="base_link">
		<visual>
			<origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
			<geometry>
				<mesh filename="~/NASA_ws/digr/description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
			</geometry>
			<material name="grey"/>
		</visual>
		
		<collision>
			<origin xzy="0 0 ${base_height/2.0}" rpy="0 0 0"/>
			<geometry>
				<box size="${base_length} ${base_width} ${base_width}"/>
			</geometry>
		</collision>
		
		<inertial>
			<origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
			<mass value="${base_mass}"/>
			<box_inertial_matrix m="${base_mass}" h="${base_height}" l="${base_length}" w="${base_width}" />
		</inertial>
	</link>
	
	
	<joint name="front_left_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="front_left_wheel"/>
		<origin xyz="${base_x_origin_to_wheel} ${base_y_origin_to_wheel_origin} 0" rpy="0 0 0"/>
		<dynamics damping="0.5" friction="0.1"/> <!-- get real later-->
		<limit effort="1000" velocity="10"/> <!-- simmulate motors, max velocity and max joint effort -->
		<axis xyz="0 1 0"/> <!-- will rotate for y axis -->
	</joint>
	
	<link name="front_left_wheel">
		<visual>
			<origin xyz="0 0 0" rpy="${PI/2.0} 0 0"/> 
			<geometry>
				<cylinder length="${wheel_height}" radius="${wheel_radius}" />
			</geometry>
			<mesh filename="~/NASA_ws/digr/description/meshes/wheel_1.stl" scale="0.001 0.001 0.001"/>
			<material name="light_black"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="${PI/2.0} 0 0" />
			<geometry>
				<cylinder length="${wheel_height}" radius="${wheel_radius}" />
			</geometry>
		</collision>
		
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="${wheel_mass}" />
			<cylinder_inertial_matrix m="${wheel_mass}" h="${wheel_height}" r="${wheel_radius}"/>
		</inertial>
	</link>
	
	<!-- Transmission sims motor control -->
	
	
	<joint name="front_right_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="front_right_wheel"/>
		<origin xyz="${base_x_origin_to_wheel} ${-base_y_origin_to_wheel_origin} 0" rpy="0 0 0"/>
		<dynamics damping="0.5" friction="0.1"/> <!-- get real later-->
		<limit effort="1000" velocity="10"/> <!-- simmulate motors, max velocity and max joint effort -->
		<axis xyz="0 1 0"/> <!-- will rotate for y axis -->
	</joint>
	
	<link name="front_right_wheel">
		<visual>
			<origin xyz="0 0 0" rpy="${PI/2.0} 0 0"/> 
			<geometry>
				<cylinder length="${wheel_height}" radius="${wheel_radius}" />
			</geometry>
			<mesh filename="~/NASA_ws/digr/description/meshes/wheel_1.stl" scale="0.001 0.001 0.001"/>
			<material name="light_black"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="${PI/2.0} 0 0" />
			<geometry>
				<cylinder length="${wheel_height}" radius="${wheel_radius}" />
			</geometry>
		</collision>
		
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="${wheel_mass}" />
			<cylinder_inertial_matrix m="${wheel_mass}" h="${wheel_height}" r="${wheel_radius}"/>
		</inertial>
	</link>
	
	
	<joint name="back_left_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="back_left_wheel"/>
		<origin xyz="${-base_x_origin_to_wheel} ${base_y_origin_to_wheel_origin} 0" rpy="0 0 0"/>
		<dynamics damping="0.5" friction="0.1"/> <!-- get real later-->
		<limit effort="1000" velocity="10"/> <!-- simmulate motors, max velocity and max joint effort -->
		<axis xyz="0 1 0"/> <!-- will rotate for y axis -->
	</joint>
	
	<link name="back_left_wheel">
		<visual>
			<origin xyz="0 0 0" rpy="${PI/2.0} 0 0"/> 
			<geometry>
				<cylinder length="${wheel_height}" radius="${wheel_radius}" />
			</geometry>
			<mesh filename="~/NASA_ws/digr/description/meshes/wheel_1.stl" scale="0.001 0.001 0.001"/>
			<material name="light_black"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="${PI/2.0} 0 0" />
			<geometry>
				<cylinder length="${wheel_height}" radius="${wheel_radius}" />
			</geometry>
		</collision>
		
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="${wheel_mass}" />
			<cylinder_inertial_matrix m="${wheel_mass}" h="${wheel_height}" r="${wheel_radius}"/>
		</inertial>
	</link>
			
	
	<joint name="back_right_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="back_right_wheel"/>
		<origin xyz="${-base_x_origin_to_wheel} ${-base_y_origin_to_wheel_origin} 0" rpy="0 0 0"/>
		<dynamics damping="0.5" friction="0.1"/> <!-- get real later-->
		<limit effort="1000" velocity="10"/> <!-- simmulate motors, max velocity and max joint effort -->
		<axis xyz="0 1 0"/> <!-- will rotate for y axis -->
	</joint>
	
	<link name="back_right_wheel">
		<visual>
			<origin xyz="0 0 0" rpy="${PI/2.0} 0 0"/> 
			<geometry>
				<cylinder length="${wheel_height}" radius="${wheel_radius}" />
			</geometry>
			<mesh filename="~/NASA_ws/digr/description/meshes/wheel_1.stl" scale="0.001 0.001 0.001"/>
			<material name="light_black"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="${PI/2.0} 0 0" />
			<geometry>
				<cylinder length="${wheel_height}" radius="${wheel_radius}" />
			</geometry>
		</collision>
		
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="${wheel_mass}" />
			<cylinder_inertial_matrix m="${wheel_mass}" h="${wheel_height}" r="${wheel_radius}"/>
		</inertial>
	</link>
	
	<!-- IMU -->
	<joint name="imu_joint" type="fixed">
		<axis rpy="0 0 0" xyz="0 1 0"/>
		<parent link="base_link" />
		<child link="imu_link" />
		<origin rp="0 0 0" xyz="0 0 ${base_height + ium_height/2.0}" />
	</joint>
	
	<link name="imu_link">
		<visual>
			<geometry>
				<box size="${imu_length} ${imu_width} ${imu_height}" />
			</geometry>
		</visual>
		
		<collision>
			<geometry>
				<box size="${imu_length} ${imu_width} ${imu_height}" />
			</geometry>
		</collision>
		
	</link>
</robot>


			
<!-- 4 cams, IMU -->
